import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import { SessionProvider } from 'next-auth/react';
import { Toaster } from '@/components/ui/sonner';
import { ThemeProvider } from '@/components/ui/theme/themeProvider';
import { GetPageName } from '@/components/pageName/pageName';
import { NotificationProvider } from '@/context/notificationContext';

const pjs = localFont({
  src: [
    {
      path: './fonts/PlusJakartaSans-ExtraLight.ttf',
      weight: '200',
      style: 'normal',
    },
    {
      path: './fonts/PlusJakartaSans-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/PlusJakartaSans-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/PlusJakartaSans-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/PlusJakartaSans-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/PlusJakartaSans-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/PlusJakartaSans-ExtraBold.ttf',
      weight: '800',
      style: 'normal',
    },
  ],
  variable: '--font-plus-jakarta-sans',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Project Management | Officehassle',
  description: 'Generated by create next app',
};

export default function RootLayout(props: any) {
  const { children } = props;
  const { session } = props;

  return (
    <html lang="en">
      <body className={`${pjs.className}`}>
        <SessionProvider session={session}>
          <NotificationProvider>
            <ThemeProvider
              attribute="class"
              disableTransitionOnChange
              defaultTheme="system"
              enableSystem
            >
              <GetPageName />

              {children}
              <Toaster />
            </ThemeProvider>
          </NotificationProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
